# Generated by Django 5.0.4 on 2024-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userregister_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
    ]
