# Generated by Django 5.0.4 on 2024-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_userregister_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='userImageURL',
            field=models.URLField(null=True),
        ),
    ]
