# Generated by Django 5.0.4 on 2024-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_userregister_userimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='userImageURL',
            field=models.CharField(null=True),
        ),
    ]
