# Generated by Django 5.0.4 on 2024-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victimName', models.CharField(max_length=55)),
                ('victimAge', models.CharField(max_length=2)),
                ('victimAddress', models.CharField(max_length=55)),
                ('victimPhoto', models.CharField(null=True)),
                ('victimCertificate', models.CharField(null=True)),
            ],
        ),
    ]
