# Generated by Django 5.0.4 on 2024-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='postDate',
            field=models.DateField(),
        ),
    ]
