# Generated by Django 5.0.4 on 2024-05-16 12:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_postdetails_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='postImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
