# Generated by Django 5.0.4 on 2024-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumpost_delete_postdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='postDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='postImage',
            field=models.FileField(null=True, upload_to='forum-post-image'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='postTime',
            field=models.TimeField(null=True),
        ),
    ]
