# Generated by Django 5.0.4 on 2024-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_forumpost_postdate_remove_forumpost_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='postDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='postTime',
            field=models.TimeField(null=True),
        ),
    ]
