# Generated by Django 5.0.4 on 2024-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
