# Generated by Django 5.0.4 on 2024-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_forumpost_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='postImage',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
