# Generated by Django 5.0.4 on 2024-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_forumpost_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
