# Generated by Django 5.0.4 on 2024-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_forumpost_latitude_forumpost_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='postImage',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='postImageURL',
            field=models.URLField(null=True),
        ),
    ]
