# Generated by Django 5.0.4 on 2024-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_forumpost_postimage_forumpost_postimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='postImageURL',
            field=models.CharField(null=True),
        ),
    ]
