# Generated by Django 5.0.4 on 2024-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_forumpost_postimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='postDate',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='postTime',
            field=models.CharField(null=True),
        ),
    ]
