# Generated by Django 5.0.4 on 2024-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_forumpost_postimageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='dangerZoneCoordandIOTPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('IOTImageURL', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
