# Generated by Django 5.0.4 on 2024-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_dangerzonecoordandiotphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IOTImageURL', models.CharField(blank=True, null=True)),
                ('is_approved', models.BooleanField(null=True)),
            ],
        ),
    ]
