# Generated by Django 5.0.4 on 2024-07-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('victim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.victim')),
            ],
        ),
    ]
